name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build-linux-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      # The docker method doesn't work on github actions, but works totally fine locally.
      # - name: Build using docker
      #   run: |
      #     cd docker
      #     chmod +x ./build.sh
      #     chmod +x ./docker-entrypoint.sh
      #     ./build.sh

      - name: Build
        run: |
          cmake --version
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j4

      - name: Create a folder for release
        shell: bash
        run: |
          mkdir dist
          cd dist
          mkdir components
          cd ..
          mv ./build/src/omp-node.so ./dist/components/omp-node.so
          mv ./deps/node/lib/linux/x64/libnode.so.108 ./dist/libnode.so.108

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omp-node-linux
          path: dist/*
